#!/usr/bin/env python3
"""
Scan place-photos/day-NN/<place_id>/ for images and write place-photos/manifest.js
so the map loads your photos automatically (no manual index.html edits).

Supported extensions: .jpg .jpeg .png .webp .gif (sorted by filename).

Usage:
  python3 scan_place_photos.py          # scan + write manifest
  python3 scan_place_photos.py --init   # create empty day/place folders first

Run scan again after adding or renaming images. Serve the site over http so manifest.js loads.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

from place_layout import PLACE_FOLDERS, day_dir_name, place_dir

ROOT = os.path.dirname(os.path.abspath(__file__))
PLACE_PHOTOS = os.path.join(ROOT, "place-photos")
EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
MANIFEST_JS = os.path.join(PLACE_PHOTOS, "manifest.js")
MANIFEST_JSON = os.path.join(PLACE_PHOTOS, "manifest.json")


def collect_manifest() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for day, pid in PLACE_FOLDERS:
        folder = place_dir(ROOT, day, pid)
        if not os.path.isdir(folder):
            continue
        names = sorted(
            f
            for f in os.listdir(folder)
            if os.path.splitext(f)[1].lower() in EXT
            and os.path.isfile(os.path.join(folder, f))
        )
        if not names:
            continue
        rel = [
            "/".join(
                ["place-photos", day_dir_name(day), pid, name]
            ).replace("\\", "/")
            for name in names
        ]
        out[pid] = rel
    return out


def write_manifest_js(manifest: dict[str, list[str]]) -> None:
    body = json.dumps(manifest, indent=2, sort_keys=True)
    text = "/* Auto-generated by scan_place_photos.py — do not edit by hand */\n"
    text += f"window.PLACE_PHOTO_MANIFEST = {body};\n"
    os.makedirs(PLACE_PHOTOS, exist_ok=True)
    with open(MANIFEST_JS, "w", encoding="utf-8") as f:
        f.write(text)
    with open(MANIFEST_JSON, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    print("wrote", MANIFEST_JS)
    print("wrote", MANIFEST_JSON)


def init_folders() -> None:
    os.makedirs(PLACE_PHOTOS, exist_ok=True)
    for day, pid in PLACE_FOLDERS:
        d = place_dir(ROOT, day, pid)
        os.makedirs(d, exist_ok=True)
        keep = os.path.join(d, ".gitkeep")
        if not os.path.isfile(keep):
            with open(keep, "w", encoding="utf-8") as f:
                f.write("")
        print("mkdir", d)


def main() -> None:
    ap = argparse.ArgumentParser(description="Scan day/place photo folders and build manifest.js")
    ap.add_argument("--init", action="store_true", help="Create place-photos/day-NN/<id>/ folders")
    args = ap.parse_args()
    if args.init:
        init_folders()
    manifest = collect_manifest()
    write_manifest_js(manifest)
    n = sum(len(v) for v in manifest.values())
    print(f"places with images: {len(manifest)}  total files: {n}")
    if not manifest:
        print(
            "Tip: add .jpg/.png under place-photos/day-NN/<place_id>/ then run this script again.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
