/* Auto-generated by scan_place_photos.py — do not edit by hand */
window.PLACE_PHOTO_MANIFEST = {
  "d1": [
    "place-photos/day-01/d1/ahmedabad-junction.webp",
    "place-photos/day-01/d1/ahmedabad-railways-station.webp"
  ],
  "d5": [
    "place-photos/day-05/d5/Naggar Castle- A Historic Gem in the Heart of Himachal Pradesh-11.jpg",
    "place-photos/day-05/d5/Naggar-Castle-near-Manali.webp",
    "place-photos/day-05/d5/NaggarCastleRainyDay.jpg",
    "place-photos/day-05/d5/Naggar_Castle_-_2.jpg",
    "place-photos/day-05/d5/caption.jpg",
    "place-photos/day-05/d5/hotel-castle-naggar.jpg",
    "place-photos/day-05/d5/naggar-179.jpeg",
    "place-photos/day-05/d5/naggar-castle-courtyard.webp",
    "place-photos/day-05/d5/naggar-castle.jpg",
    "place-photos/day-05/d5/naggar-castle.webp",
    "place-photos/day-05/d5/naggar-manali-himachal-pradesh-1-musthead-hero.jpeg",
    "place-photos/day-05/d5/naggar-manali-himachal-pradesh-2-attr-hero.jpeg",
    "place-photos/day-05/d5/naggar-manali-himachal-pradesh-6-musthead-hero.jpeg",
    "place-photos/day-05/d5/naggar-town-viewpoint.webp",
    "place-photos/day-05/d5/naggar-village.webp",
    "place-photos/day-05/d5/naggar.jpg"
  ],
  "d8b": [
    "place-photos/day-08/d8b/kullu-river-rafting.jpg"
  ],
  "d9a": [
    "place-photos/day-09/d9a/1_result-1675091096703.webp",
    "place-photos/day-09/d9a/343cb332880611ec93680a58a9feac02.jpg",
    "place-photos/day-09/d9a/Dobhi-Paragliding-840x425.jpg",
    "place-photos/day-09/d9a/Exterior-2-Dreams-Streams-Homestay-Dobhi-Kullu.jpg",
    "place-photos/day-09/d9a/G0010862.jpg",
    "place-photos/day-09/d9a/IMG_20181027_112052.jpg",
    "place-photos/day-09/d9a/Paragliding-in-Dobhi-560x460.jpeg",
    "place-photos/day-09/d9a/dobhi-is-one-of-the-newest.jpg",
    "place-photos/day-09/d9a/e4b289c83e3e4101bf760e3167efe177.webp",
    "place-photos/day-09/d9a/images.jpeg",
    "place-photos/day-09/d9a/kullu-river-rafting.jpg",
    "place-photos/day-09/d9a/mahadev-xtream-adventures-kullu-ho-kullu-car-hire-0ro7is58as.jpg",
    "place-photos/day-09/d9a/nx86u6cs6nse664nb3ltacfrgbil_shutterstock_1362733667 (1).jpg",
    "place-photos/day-09/d9a/outer-view-with-peace.jpg",
    "place-photos/day-09/d9a/rapid-riders-manali-ho-manali-travel-agents-334o70h.jpg",
    "place-photos/day-09/d9a/shri-krishna-adventure-136-rafting-and-paragliding-babeli-kullu-trekking-organisers-193b02ynba.webp"
  ],
  "d9b": [
    "place-photos/day-09/d9b/1d3e0af6-21a7-4ff7-99f7-0c8d38fc1f30.jpeg",
    "place-photos/day-09/d9b/Hadimba-Devi-Temple.jpg",
    "place-photos/day-09/d9b/Hadimba_Devi_Temple_2.jpg",
    "place-photos/day-09/d9b/Hidimba-Devi-Temple-Manali.jpg",
    "place-photos/day-09/d9b/hidimba-temple-manali-himachal-pradesh-1-musthead-hero.jpeg",
    "place-photos/day-09/d9b/hidimba-temple-manali-himachal-pradesh-2-attr-hero.jpeg",
    "place-photos/day-09/d9b/hidimba-temple-manali-himachal-pradesh-5-musthead-hero.jpeg",
    "place-photos/day-09/d9b/m_activities-manali-hidimba-devi-temple_l_400_640.jpg"
  ],
  "d9c": [
    "place-photos/day-09/d9c/129084912Manali_Manu_Temple_Main.jpg",
    "place-photos/day-09/d9c/Blue Travel Meenakshi Temple YouTube Thumbnail (21).png",
    "place-photos/day-09/d9c/DSC4041.webp",
    "place-photos/day-09/d9c/Manu-Temple-cover-image-840x425.jpg",
    "place-photos/day-09/d9c/Shanshar-8.jpg",
    "place-photos/day-09/d9c/m_Manu Temple_1_l_416_609.jpg",
    "place-photos/day-09/d9c/manu temple kulu - manali.webp",
    "place-photos/day-09/d9c/manu-temple-old-manali-entry-ticket-price-manali-tourism.jpg.jpg",
    "place-photos/day-09/d9c/manu-temple.jpg",
    "place-photos/day-09/d9c/manu-temple.webp",
    "place-photos/day-09/d9c/uvmu66pijbizlfd9xn2bt78wgfdi_1577359509_shutterstock_1382576963.webp"
  ]
};
